apiVersion: v1
kind: Service
metadata:
  name: monitor-api
  namespace: supply-chain-monitor
spec:
  selector:
    app: monitor-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30300
  type: NodePort
