#!/usr/bin/env bash
# Creates the GPG keypair the Postgres backup CronJob encrypts to, and
# installs the PUBLIC half as the scm-backup-encryption Secret.
#
# WHY THIS EXISTS
#
# Nothing created this Secret. The chart mounts it non-optionally when
# postgres.backup.encryption.publicKeySecret is set (deliberately: a
# missing key must stop the pod, not silently fall back to writing
# plaintext under a config that says it encrypts) -- so a cluster
# rebuilt without it has a backup job that CrashLoops nightly. That is
# exactly what happened on 2026-09-03: everything else came back from
# git and this one piece of state did not, because it only ever existed
# in someone's shell history.
#
# THE ASYMMETRY IS THE POINT. The cluster gets the half that ENCRYPTS
# and nothing else -- it cannot read a single dump, including the ones
# it wrote itself. The half that decrypts lives here, outside the
# cluster, and is lent to a restore for the seconds it runs (see
# cluster/postgres-restore.sh's GPG_PRIVATE_KEY_FILE).
#
# So: lose the private key and every backup you hold is scrap. This
# script never deletes one, and never overwrites one -- every file it
# writes is named for the key's own fingerprint.
#
# ROTATION DOES NOT RE-ENCRYPT ANYTHING. A backup is encrypted to
# whichever public key was current when it was written, so after
# --rotate every EXISTING backup still needs the OLD private key and
# always will. Rotating on a leak and then deleting the old key leaves
# you with zero restorable backups. --rotate says so, and tells you how
# to close the window immediately.
#
# Usage:
#   ./cluster/backup-encryption-key.sh            # first run
#   ./cluster/backup-encryption-key.sh --rotate   # leaked/retired key
#   GPG_PRIVATE_KEY_FILE=... ./cluster/backup-encryption-key.sh --check
#
#   SCM_BACKUP_KEY_DIR=/path   where private keys live (default ~/.scm-backup-keys)
#   NAMESPACE=...              default supply-chain-monitor
#
# No passphrase is set on the key. The file mode (0600) in a directory
# only you can read is the protection; a passphrase stored next to the
# key it protects adds nothing. cluster/postgres-restore.sh does accept
# one (GPG_PASSPHRASE_FILE) if you add it yourself later.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$DIR/.." && pwd)"
CHART="charts/supply-chain-monitor"
NAMESPACE="${NAMESPACE:-supply-chain-monitor}"
SECRET_NAME="scm-backup-encryption"
KEY_DIR="${SCM_BACKUP_KEY_DIR:-$HOME/.scm-backup-keys}"

MODE="create"
case "${1:-}" in
	--rotate) MODE="rotate" ;;
	--check)  MODE="check" ;;
	-h|--help) sed -n '2,45p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
	"") ;;
	*) echo "unknown argument: $1 (try --help)" >&2; exit 2 ;;
esac

for t in kubectl docker; do
	command -v "$t" >/dev/null 2>&1 || { echo "ERROR: $t not found on PATH." >&2; exit 1; }
done

# THE SAME IMAGE THE BACKUP AND RESTORE JOBS RUN, read from values.yaml
# rather than pinned here -- a key generated by a different gpg than the
# one that has to decrypt it is the one failure this script exists to
# rule out, so it must not drift onto a different image. Same read as
# cluster/test-backup-scripts.sh.
PG_IMAGE="$(python3 - "$ROOT/$CHART/values.yaml" <<'PY'
import sys, yaml
v = yaml.safe_load(open(sys.argv[1]))["postgres"]["image"]
print(f'{v["repository"]}:{v["tag"]}')
PY
)"

# Inside the repo, not $TMPDIR: on macOS mktemp -d lands in /var/folders,
# which Docker Desktop does not share, so the mount would silently be an
# empty directory. Same reason as cluster/test-backup-scripts.sh.
WORK="$(mktemp -d "$ROOT/.backup-key-work.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT

# --user 0: the Percona image runs as uid 26 and $WORK belongs to
# whoever ran this. Docker Desktop fakes bind-mount ownership so this
# only bites on Linux.
in_pg() { docker run --rm --user 0 -v "$WORK":/w -w /w --entrypoint sh "$PG_IMAGE" -c "$1"; }

# Encrypt with the CronJob's EXACT invocation (backup-cronjob.yaml's
# encrypt()), then decrypt the way postgres-restore-job.template.yaml
# does. Encrypting by --recipient-file against the very bytes bound for
# the Secret is the whole point: --import plus --recipient <uid> is a
# different code path with different trust handling, and would pass here
# while the real job failed.
roundtrip() {
	# SC2016: single quotes are the point -- this is a script for the
	# container, and $GNUPGHOME must be expanded by ITS shell, not this one.
	# shellcheck disable=SC2016
	in_pg '
		set -e
		export GNUPGHOME=/w/verify-home
		rm -rf "$GNUPGHOME"; mkdir -p "$GNUPGHOME"; chmod 700 "$GNUPGHOME"
		head -c 200000 /dev/urandom > /w/sample.bin
		gpg --batch --yes --quiet --no-options --trust-model always \
			--recipient-file /w/publickey.asc -z 0 --encrypt \
			< /w/sample.bin > /w/sample.gpg
		gpg --batch --quiet --no-options --import /w/privatekey.asc 2>/dev/null
		gpg --batch --quiet --no-options --decrypt /w/sample.gpg > /w/sample.out 2>/dev/null
		# sha256sum, not cmp: this image has no cmp and no diff, and the
		# whole point of running in THIS image is that it is the one that
		# has to do the real work.
		[ "$(sha256sum < /w/sample.bin | cut -d" " -f1)" \
		  = "$(sha256sum < /w/sample.out | cut -d" " -f1)" ]
	'
}

if [ "$MODE" = "check" ]; then
	KEYFILE="${GPG_PRIVATE_KEY_FILE:-}"
	[ -n "$KEYFILE" ] || { echo "ERROR: --check needs GPG_PRIVATE_KEY_FILE=/path/to/...private.asc" >&2; exit 2; }
	[ -s "$KEYFILE" ] || { echo "ERROR: $KEYFILE is missing or empty." >&2; exit 1; }
	echo "== checking the private key against the key the cluster is encrypting to =="
	kubectl -n "$NAMESPACE" get secret "$SECRET_NAME" \
		-o jsonpath='{.data.publickey\.asc}' 2>/dev/null | base64 --decode > "$WORK/publickey.asc" \
		|| { echo "ERROR: no $SECRET_NAME Secret in namespace $NAMESPACE." >&2; exit 1; }
	[ -s "$WORK/publickey.asc" ] || { echo "ERROR: $SECRET_NAME has no publickey.asc key." >&2; exit 1; }
	cp "$KEYFILE" "$WORK/privatekey.asc"
	if roundtrip; then
		echo "  ok:   this private key decrypts what the cluster encrypts."
		echo
		echo "That covers new backups. It does NOT prove an OLDER backup is readable --"
		echo "each one is encrypted to whatever key was current when it was written."
		echo "To check a specific backup, restore it: make db-backups-list, then"
		echo "  make db-restore BACKUP=<name> GPG_PRIVATE_KEY_FILE=$KEYFILE"
		exit 0
	fi
	echo "  FAIL: this private key does NOT decrypt what the cluster encrypts." >&2
	echo "  Backups being written right now are not readable with $KEYFILE." >&2
	echo "  Look in $KEY_DIR for the key matching the current Secret, or --rotate." >&2
	exit 1
fi

EXISTS=no
kubectl -n "$NAMESPACE" get secret "$SECRET_NAME" >/dev/null 2>&1 && EXISTS=yes

if [ "$EXISTS" = yes ] && [ "$MODE" = create ]; then
	cat >&2 <<EOF
ERROR: $SECRET_NAME already exists in namespace $NAMESPACE.

Replacing the key it holds makes every backup written from now on
unreadable with the private key you currently have -- so this is never
something to do by accident.

  ./cluster/backup-encryption-key.sh --rotate       # you mean it
  GPG_PRIVATE_KEY_FILE=... $0 --check               # just checking it works
EOF
	exit 1
fi

mkdir -p "$KEY_DIR"
chmod 700 "$KEY_DIR"

echo "== generating a keypair in ${PG_IMAGE} =="
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
UID_NAME="scm-backup-${STAMP}"

# NEVER EXPIRES, on purpose. An expiry gives you a backup job that
# succeeds for a year and then fails every night -- the same shape, and
# the same silence, as the cert-manager webhook certificate that froze
# this cluster for three days. Rotation here is a decision someone
# makes, not a clock going off. Retire a key with --rotate.
in_pg "
	set -e
	export GNUPGHOME=/w/home
	mkdir -p \"\$GNUPGHOME\"; chmod 700 \"\$GNUPGHOME\"
	gpg --batch --quiet --passphrase '' \
		--quick-generate-key '${UID_NAME}' default default never
	gpg --armor --export '${UID_NAME}' > /w/publickey.asc
	gpg --armor --batch --pinentry-mode loopback --passphrase '' \
		--export-secret-keys '${UID_NAME}' > /w/privatekey.asc
	gpg --batch --with-colons --fingerprint '${UID_NAME}' \
		| awk -F: '/^fpr:/{print \$10; exit}' > /w/fpr
"
[ -s "$WORK/publickey.asc" ] && [ -s "$WORK/privatekey.asc" ] \
	|| { echo "ERROR: key generation produced an empty file." >&2; exit 1; }
FPR="$(cat "$WORK/fpr")"
echo "  ${UID_NAME}  ${FPR}"

# BEFORE the Secret is touched. A key that cannot round-trip must never
# reach the cluster -- installing it would swap working encryption for
# backups nobody can read, and the job would report success throughout.
echo "== verifying the pair round-trips through the real gpg =="
if roundtrip; then
	echo "  ok:   200000 random bytes encrypted to the public key and decrypted byte-identically"
else
	echo "  FAIL: the generated pair does not round-trip. Nothing was changed." >&2
	exit 1
fi

PRIV="$KEY_DIR/scm-backup-${STAMP}-${FPR:0:8}.private.asc"
PUB="$KEY_DIR/scm-backup-${STAMP}-${FPR:0:8}.public.asc"
# Named for its own fingerprint, so no run can ever overwrite an earlier
# key -- an overwritten private key is every backup encrypted to it lost.
[ -e "$PRIV" ] && { echo "ERROR: $PRIV already exists; refusing to overwrite." >&2; exit 1; }
install -m 600 "$WORK/privatekey.asc" "$PRIV"
install -m 644 "$WORK/publickey.asc" "$PUB"

echo "== installing the public half as $SECRET_NAME in $NAMESPACE =="
# create|apply rather than plain create: --rotate has to replace one.
kubectl -n "$NAMESPACE" create secret generic "$SECRET_NAME" \
	--from-file=publickey.asc="$WORK/publickey.asc" \
	--dry-run=client -o yaml | kubectl -n "$NAMESPACE" apply -f - >/dev/null
echo "  ok:   Secret written (public key only -- the cluster cannot decrypt)"

echo
echo "Private key: $PRIV"
echo "  mode 0600, and NOT in this repo. Back it up somewhere you would still"
echo "  have if this machine died -- it is the only thing that can read a backup."
echo
echo "Restore with:"
echo "  make db-restore BACKUP=<name> GPG_PRIVATE_KEY_FILE=$PRIV"

if [ "$MODE" = rotate ]; then
	cat <<EOF

== ROTATED -- read this ==

Every backup written BEFORE now is encrypted to the OLD public key and
always will be. This new key cannot read any of them. Rotation does not
re-encrypt anything.

So until a NEW backup exists and you have decrypted it, your only
restorable backups are the old ones, and they need the old private key.
Do not delete it yet -- do not delete it at all until you are certain no
backup you would ever want is still encrypted to it.

Close that window now rather than waiting for 02:00:

  kubectl create job -n $NAMESPACE --from=cronjob/scm-postgres-backup backup-after-rotation
  kubectl logs -n $NAMESPACE job/backup-after-rotation
  make db-backups-list
  make db-restore BACKUP=<the new one> GPG_PRIVATE_KEY_FILE=$PRIV

Keys in $KEY_DIR:
EOF
	# SC2012: our own filenames, scm-backup-<ISO stamp>-<hex>.private.asc,
	# with no spaces or newlines possible.
	# shellcheck disable=SC2012
	ls -1 "$KEY_DIR"/*.private.asc 2>/dev/null | sed 's/^/  /'
fi
