apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: scm-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scm-registry
  template:
    metadata:
      labels:
        app: scm-registry
    spec:
      containers:
        - name: registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: {{ .Values.deleteEnabled | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
          readinessProbe:
            httpGet:
              path: /v2/
              port: 5000
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              path: /v2/
              port: 5000
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: scm-registry-data
